### ISSUE TITLE
Unicode error when running strip hints

### ISSUE THREAD

**Issue by paulgc** [abarker/strip-hints#5]
Processing python file tensorflow_data_validation/coders/csv_decoder_test.py
Traceback (most recent call last):
  File "tensorflow_data_validation/tools/strip_type_hints.py", line 58, in <module>
    main()
  File "tensorflow_data_validation/tools/strip_type_hints.py", line 54, in main
    strip_all_type_hints(repo_base)
  File "tensorflow_data_validation/tools/strip_type_hints.py", line 39, in strip_all_type_hints
    only_test_for_changes=False)
  File "/usr/local/home/miniconda2/lib/python2.7/site-packages/strip_hints/strip_hints_main.py", line 366, in strip_file_to_string
    processed_code = stripper.strip_type_hints_from_file(filename)
  File "/usr/local/home/miniconda2/lib/python2.7/site-packages/strip_hints/strip_hints_main.py", line 345, in strip_type_hints_from_file
    result = tokens.untokenize()
  File "/usr/local/home/miniconda2/lib/python2.7/site-packages/strip_hints/token_list.py", line 233, in untokenize
    decoded_result = result.decode(encoding)
  File "/usr/local/home/miniconda2/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6288-6295: ordinal not in range(128)

**Comment by abarker** [comment]
I was able to reproduce the bug when running strip-hints with Python 2 on a file containing a unicode string.  It does not occur when running strip-hints with Python 3.  The preferred solution would be to use Python 3 to run strip-hints if that is possible.

I have pushed a new version of strip-hints that seems to fix the issue on my machine when running with Python 2.

**Comment by ReenigneArcher** [comment]
I am getting this error when running the code in Python 2.7, using the latest version of the pypi package. It works under Python 3, but kind of hacky to use in my CI since I now need to install another version of python.
